name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test-library:
    name: "Library"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.x
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint Addon
        run: pnpm run lint
        working-directory: addon
      - name: Lint Test App
        run: pnpm run lint
        working-directory: test-app
      - name: Run Tests
        run: pnpm run test:ember
        working-directory: test-app

  test-library-floating:
    name: "Library - Floating Dependencies"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.x
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --no-lockfile
      - name: Run Tests
        run: pnpm run test:ember
        working-directory: test-app

  test-docs:
    name: "Docs"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.x
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run lint
        working-directory: docs
      - name: Run Tests
        run: pnpm run test:ember
        working-directory: docs

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: 'test-library'

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-lts-3.24
          - ember-lts-3.28
          - ember-release
          - ember-beta
          - ember-canary
          - ember-classic
          - embroider-safe
          - embroider-optimized

    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.x
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Tests
        run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
        working-directory: test-app

  typescript-compatibility:
    if: ${{ false }}  # disable for now
    name: Type checking - ${{ matrix.typescript-scenario }}
    runs-on: ubuntu-latest
    needs: 'test-library'

    strategy:
      fail-fast: false
      matrix:
        typescript-scenario:
          - typescript-4.2
          - typescript-4.3
          - typescript-4.4
          - typescript-4.5
          - typescript-next

    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.x
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Type checking
        run: ./node_modules/.bin/ember try:one --config-path="./config/ember-try-typescript.js" ${{ matrix.typescript-scenario }}
        working-directory: test-app
